server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: pickup
          uri: http://localhost:8081
          predicates:
            - Path=/laundryHistories/**, /laundryStatuses/**
        - id: payment
          uri: http://localhost:8082
          predicates:
            - Path=/paymentHistories/**, 
        - id: laundryprovider
          uri: http://localhost:8083
          predicates:
            - Path=/laundryHistories/**, 
        - id: 알람
          uri: http://localhost:8084
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: pickup
          uri: http://pickup:8080
          predicates:
            - Path=/laundryHistories/**, /laundryStatuses/**
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/paymentHistories/**, 
        - id: laundryprovider
          uri: http://laundryprovider:8080
          predicates:
            - Path=/laundryHistories/**, 
        - id: 알람
          uri: http://알람:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
